language: go

go:
  - "1.12"
  - "1.13"
  - "1.14"
  - "stable"

env:
  GO111MODULE=on

install:
  - mkdir -p $GOPATH/bin
  - go get github.com/go-playground/overalls
  - make deps

script:
  - make test
  - $GOPATH/bin/overalls -project=github.com/hellofresh/stats-go -covermode=count
  - bash <(curl -s https://codecov.io/bash) -f overalls.coverprofile
